import Head from 'next/head'

import Features from '@/components/Features/Features'
import Footer from '@/components/Footer/Footer'
import Hero from '@/components/Hero/Hero'
import Navbar from '@/components/Navbar/Navbar'
import Testimonials from '@/components/Testimonials/Testimonials'

export default function Home() {
  return (
    <>
      <Head>
        <title>Banks of Georgia | BOG, TBC, Liberty</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <Testimonials />
      <Features />
      <Footer />
    </>
  )
}
